default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: voyage_development
test:
  <<: *default
  database: voyage_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
